# Generated by Django 2.2 on 2019-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveIntegerField()),
                ('floor', models.IntegerField()),
                ('beds', models.PositiveIntegerField()),
                ('room_details', models.TextField()),
                ('rent', models.PositiveIntegerField()),
            ],
        ),
    ]
