# Generated by Django 2.2 on 2019-04-18 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveIntegerField()),
                ('floor', models.IntegerField()),
                ('rent', models.PositiveIntegerField()),
                ('advanced_payment', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
