# Generated by Django 2.2 on 2019-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanager', '0002_peoples'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='free_beds',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
